### ISSUE TITLE
SyntaxError: Unexpected token v

### ISSUE THREAD

**Issue by irom77** [VivekPanyam/Plotter#2]
I setup server and got 'ok' when connected. Then I tried to post JSON below

curl -i -H "Accept: application/json" -H "Content-type: application/json" -d ' {"chartID" : value, "chartID2": value2}' -X POST http://serverIP:5858/data/INSERT_AUTH_KEY_HERE/JSON

but get 

HTTP/1.1 400 Bad Request
X-Powered-By: Express
Content-Type: text/plain
Content-Length: 313
Date: Sat, 28 Nov 2015 14:05:41 GMT
Connection: keep-alive

SyntaxError: Unexpected token v
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/irek/plotter/node_modules/express/node_modules/connect/lib/middleware/json.js:66:27)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by VivekPanyam** [comment]
`{"chartID" : value, "chartID2": value2}` is not valid JSON. Replace `value` and `value2` with numbers.

In the examples, `value` and `value2` are always numbers. I'll make that more clear. 

Also, the JSON should actually be in the URL. Make a GET request to `http://localhost:8000/data/INSERT_AUTH_KEY_HERE/{"Signups":{"Web":12,"Mobile":10}}` for example. If you want to implement a cleaner way of doing this, I'd love a pull request! (My initial use case had some constraints that made JSON in the URL the easiest way of sending data)
